<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MailNotification.Application\MailNotification.Application.csproj" />
    <ProjectReference Include="..\MailNotification.Domain\MailNotification.Domain.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common.Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common.SecretBase\Common.SecretBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
