<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.5.2" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Category.Application\Category.Application.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common.Infrastructure\Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common.Exception\Common.Exception.csproj" />
    <ProjectReference Include="..\..\..\AbstractionBlocks\Common\Common.csproj" />
  </ItemGroup>

</Project>
